version: 2
jobs:
  deploy:
    working_directory: /go/src/github.com/kelvintaywl/goreview
    docker:
      - image:  circleci/golang:1.9
    steps:
      - run:
          name: todo
          command: |
            echo "need to set up steps to push image to docker hub"
  build:
    working_directory: /go/src/github.com/kelvintaywl/goreview
    docker:
      - image: circleci/golang:1.9
    steps:
        - checkout
        - run:
            name: install dep
            command: |
              make init
        - run:
            name: unit test
            command: |
              make coverage
              bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - deploy
