version: 2

dependencies:
  cache_directories:
    - ~/docker

jobs:
  deploy:
    working_directory: /go/src/github.com/kelvintaywl/goreview
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dep
          command: |
            make init
      - run:
          name: docker build
          command: |
            make docker_build
      - run:
          name: push container to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_KEY
            docker push kelvintaywl/goreview:latest
  build:
    working_directory: /go/src/github.com/kelvintaywl/goreview
    docker:
      - image: circleci/golang:1.9
    steps:
        - checkout
        - run:
            name: install dep
            command: |
              make init
        - run:
            name: unit test
            command: |
              make coverage
              bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /.*/
